# Generated by Django 4.2 on 2025-10-19 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
