# Generated by Django 4.2 on 2025-10-19 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_ultima_modificacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
